services:
  octosynk:
    image: ghcr.io/jmcharter/octosynk:latest
    container_name: octosynk
    env_file:
      - .env
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.octosynk-sync.schedule: "@every 5m"
      ofelia.job-exec.octosynk-sync.command: "octosynk"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - octosynk
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
